# -*- coding: utf-8 -*-
"""ASSIGNMENT 12A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ8LIb8HhdCmvrDMNomOcUO-nIdnH3Ie

Assignment

Data Science Masters

Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

import seaborn as sns
import plotly.graph_objects as go

tit = sns.load_dataset('titanic')

fig = go.Figure()

tit

fig.add_trace(go.Scatter(x=tit.age,y= tit.fare,mode = 'markers'))

"""Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import plotly.express as px

df = px.data.tips()

df

fig = px.box(df, x="day", y="total_bill", color="sex", title="Box Plot of Total Bill by Day and Sex")

fig

tip = sns.load_dataset('tips')

tip

"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

px.histogram(data_frame =tip,x = "sex",y= "total_bill",pattern_shape = "smoker",color = "day")

"""Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.
"""

iris = sns.load_dataset('iris')

px.scatter_matrix(data_frame = iris,color = "species",dimensions= ["sepal_length", "sepal_width", "petal_length", "petal_width" ])

"""Q5. What is Distplot? Using Plotly express, plot a distplot.

displot is a function from the Seaborn library in Python, used for creating distribution plots. It is a versatile function that can display various types of distribution plots, such as histograms, kernel density estimates, and ECDFs.
"""

import plotly.express as px

import numpy as np
data = np.random.normal(0, 1, 1000)

fig = px.histogram(data, nbins=30, title="Distribution Plot")
fig.show()

